export const GET_DATA = 'GET_DATA';

export const SET_ACTIVETAG = 'SET_ACTIVETAG';

export const SET_FOCUSITEM = 'SET_FOCUSITEM';

export const SET_LOADING = 'SET_LOADING';

export const SET_ITEMIDTOUPDATE = 'SET_ITEMIDTOUPDATE';
